### PR TITLE
Allow self-hosted for GHE and Slack Grid

### PR DESCRIPTION
**Pull request by barlock**
**Related Issues**
#565 #767

**What does this PR do?**  
Allows for the app to be self-hosted supporting Github Enterprise (server 😉) and a specific Enterprise Grid instance.

- Removes hard coded references to github.com and allows the `probot` env variable `GHE_HOST` 
- Allows for self signed certs to be passed in for redis and postgres. (I don't understand why, but that's the only option I have in my hosted environment)
- Upgrades OAuth from workspace tokens to `v2`. 
  - Needed for new apps as you can't create "Workspace" apps anymore
  - @aoberoi (DevRel from Slack) is going to help review this to make sure that oAuth doesn't break on the "production" instance. 
- Lets you customize a `SLACK_ENTERPRISE_ID` that allow allows installs for workspaces in that account
  - Prevents information leakage from url unfurls. 

**What gif most accurately describes how I feel towards this PR?**

### CODE REVIEW

**Comment by aoberoi** [comment]
I'm excited about this! It's going to take me a few days to conduct a review, but I'm happy to help.

Just so we're clear on expectations for not breaking production, we're aiming for the following:
* for existing deployments, installations in Slack with a Workspace token (`xoxa`), should continue working without any user-facing changes. simply updating the deployment to this version will preserve all existing functionality in those Workspaces.
* for existing deployments, all new installations will occur using the OAuth 2.0 v2 (aka new Slack apps, aka granular bot permissions) and result in an `xoxb` token.
* a single deployment can support both installations with a workspace token (`xoxa`) and installations using OAuth 2.0 v2 (`xoxb`) at the same time.

☝️ That's all requirements I just made up based on my understanding of how this repo is used by the deployment which supports the Slack App Directory, and will now be expected to work for on-prem or self-hosted deployments. But please correct me if I'm wrong!

**Question**: Does this PR already, or should it, add a user-facing means to ask a user to "upgrade" their installation (transition from using an `xoxa` to an `xoxb`)? If we made this a requirement, we could gradually start reducing the number of Workspace App installations that exist in the wild. We'd have to carefully consider which users, how, and when they should be prompted to "upgrade".

**Comment by barlock** [comment]
> Does this PR already, or should it, add a user-facing means to ask a user to "upgrade" their installation.

No it doesn't. I think that would live better in a separate pr. I also noticed that the app still uses `verification tokens` instead of the newer `signing secret`, which would fit well in another PR too.

**Comment by bar** [comment]
@barlock do you know why the changes have not been approved? I understand the GH team have plans to support GHE server and grid which might be already in the works?

**Comment by barlock** [comment]
Nope, not sure why this PR hasn't gotten any attention. 

I've got it deployed within my Company and it's been working pretty well. There are a few things where the App's UX isn't super great for non-workspace tokens, but it's pretty good for the effort.

**Comment by yaustar** [comment]
Bump! Would love to see this integrated for enterprise support too.

**Comment by redrac** [comment]
Bumping as well! We would love to use this at our company with grid and GHE server as well!

**Comment by hmc-cs-mdrissi** [comment]
One issue that appears to be true is no one from github is a participant in this pr. The one person you @aoberoi isn't at github anymore so would be unlikely to review. Some people that could maybe review, @julian-alarcon or @ashokirla . Looking at a comment from another pr, 

> @jmfrancois Thanks for your contribution. Unfortunately, we are not taking contributions at this point due to few platform changes. We will move this request to our backlog and take it up separately.

I'm unsure as to the state of this repository for new features.

**Comment by ashokirla** [comment]
Hi, Thanks for your contribution. We are going through platform changes to our ChatOps app and are not accepting any external contributions. However, we are currently working on adding support for GHES and Enterprise grid. We will look into your suggestions as part of it.

**Comment by barlock** [comment]
🙇 Keep me posted and if you open source it drop a link! I'd love to contribute. 

I'd also love to shut down the instance I run which is _very_ buggy as I obviously can't get workspace tokens anymore.

**Pull request closed without merging**
