### PR TITLE
Upgrade to the new @slack/web-api client

### LINKED ISSUE #540: Slack deprecation: oauth.token => oauth.access
Via https://api.slack.com/changelog/2018-04-oauth-flow-changes-for-workspace-token-preview-apps:

> Now you can exchange `code` values for tokens using `oauth.access`, just like traditional Slack apps. The output received from `oauth.access` is the same as found in `oauth.token`.

We're currently using `oauth.token` here: 
https://github.com/integrations/slack/blob/master/lib/slack/oauth.js#L56

### LINKED ISSUE #767: Migrate away from being a Slack "Workspace App"
It appears that contributing to this integration is not possible right now because per the [Contributing Docs](https://github.com/abinoda/slack/blob/master/CONTRIBUTING.md#getting-started), local development requires a Slack Workspace app, which can no longer be created.

I'm aware that there are plans to do this migration in the future but I'm wondering if there's a short-term workaround so local development is possible?

### LINKED ISSUE #769: User tokens do not support scope: chat:write
I followed directions and `CONTRIBUTING.md` as precise as I could and when I finally hit "Add to slack" button at my `https://DOMAIN/` page, I get the following error:
```
Invalid permissions requested
User tokens do not support scope: chat:write
```
What am I doing wrong?

### PR DESCRIPTION
**Pull request by kavdev**
Slack deprecated its workspace token developer preview, which caused much of this app's functionality to stop working. The new client supports bot tokens, which is an iteration on the features that came with workspace tokens.

This update replaces all the workspace token code with bot token code, and exposes new SlackWorkspace.userClient and SlackWorkspace.botClient shortcut properties to use either a user token or a bot token on various endpoints (some endpoints only support one token type).

See also https://slack.dev/node-slack-sdk/web-api

Fixes #769, Fixes #767, Fixes #540
Superceeds / Closes #711

There's also a tack-on commit that adds a quick debug command for those who use vscode. It can be droped if need be.

cc @myles2007 @scepticulous

### CODE REVIEW

**Comment by tebriel** [comment]
Hey, sorry for the long poll on responses. Beyond workspace apps being deprecated, will all current slack installs need to be re-authorized to allow use/generation of the bot token? I think we want to (if we can) avoid making every user re-authorize or re-install the github slack app.

**Comment by kavdev** [comment]
@tebriel I'm not sure. Is there someone at Slack we could ping to find out?

**Comment by tebriel** [comment]
Yeah I’ll reach out to support. Thanks @kavdev!

**Comment by kavdev** [comment]
@tebriel any movement on this?

**Comment by tebriel** [comment]
Hey @kavdev, we're engaging with Slack Support, but do not have a path forward yet. We have meetings scheduled to plan a way forward, as we want to avoid making every installed slack app re-auth unless there really is no other way (which is why right now we're tied to workspace apps). I'm sorry I don't have more detailed information/plans yet.

**Comment by kavdev** [comment]
No worries! I'll check back in occasionally.

**Comment by bruno-ortiz** [comment]
@tebriel any news on this?

**Comment by tebriel** [comment]
@bruno-ortiz a new team within GitHub is taking over the slack integration and will be responsible for migrating the app to the new Granular Bot Token Slack Application model, that work must be completed before the end of this year (due to requirements from Slack). That's all the details I have for you at this time, thank you!

**Comment by ashokirla** [comment]
As we have rolled out a new version of Slack app with Granular Bot Permissions, I assume this PR is no longer needed. 
If you still facing any problem, please raise an issue.

**Pull request closed without merging**
