### PR TITLE
Adds capability of ignoring selected label in the subscription

### PR DESCRIPTION
**Pull request by yudppp**
This change implements issue #951 - you can specify -label if you
want to ignore pull requests with the specified label.

And Cherry picked https://github.com/integrations/slack/pull/974.

### CODE REVIEW

**Comment by steve-taylor** [comment]
> We are currently not accepting any contributions to this app. You can raise a feature request from [here](https://github.com/integrations/slack/issues/new)

*"Pull requests for thee, but not for me"* - GitHub

**Comment by ScottKaye** [comment]
> We are currently not accepting any contributions to this app. You can raise a feature request from [here](https://github.com/integrations/slack/issues/new)

Why not?

**Comment by Oliniusz** [comment]
Corporate politics - the whole open source code got removed from this repository in June 2021 and since then only the `README.md` file is getting changed every few weeks by a few Asian guys.

**Comment by iamstarkov** [comment]
@ScottKaye you happen to link it to this very repo, did anything happen in the last year?

**Comment by ScottKaye** [comment]
> @ScottKaye you happen to link it to this very repo, did anything happen in the last year?

No idea, this repo appears to be dead or it has changed direction.  I don't think anything is ever going to happen here unfortunately.

**Comment by gr2m** [comment]
closing as the pull request is obsolete, code was moved to a private repository.

**Pull request closed without merging**
