### PR TITLE
Support for commit comments

### PR DESCRIPTION
**Pull request by artnez**
As requested in #432 

Note: This enables commit comments when the `comments` setting is turned on. That means all existing users who have the `comments` setting enabled will be automatically opted into commit comments.

### CODE REVIEW

**Comment by artnez** [comment]
Just realized this is PR #666 🎸

**Comment by ayyazdaniaryan** [comment]
Cool! A sorely missed feature is coming back to life :). I think this is a great integration as is. Only part I would suggest (perhaps for a future PR) is to keep this logic and update the `Comment` object on the `edit_comment` hook. This will keep the integration clean and consistent with issue comments. Not picky at all, btw, this is great, and I cannot wait for it to be merged so we can update our slack integration and be able to read commit comments again. Thank you @artnez !

**Comment by artnez** [comment]
@ayyazdaniaryan I attempted adding support for commit comment editing but couldn't find the right webhook event. 

The issue comment event has created/edited/deleted actions:
https://developer.github.com/v3/activity/events/types/#issuecommentevent

Same for pull request review comments:
https://developer.github.com/v3/activity/events/types/#pullrequestreviewcommentevent

The commit comment event only has created though:
https://developer.github.com/v3/activity/events/types/#commitcommentevent

**Comment by webdif** [comment]
Our team is still using old slack integration because of the lack of this feature.
@bkeepers it would be really great if you have time to see this PR 🙏

**Comment by artnez** [comment]
@bkeepers I noticed you updated to Probot 7 so I made the necessary changes on my end as well. The only thing I needed to do was rename `event` to `name` in my tests. Everything else continues to work.

**Comment by bkeepers** [comment]
@artnez thanks so much for working this. This PR looks great! It's deployed to production.

---

image

**Pull request merged**
