### PR TITLE
Add wiki notification support

### LINKED ISSUE #410: Support notifications on Wiki updates
It'd be great to be able to subscribe to get notifications on Wiki updates, which is currently not supported.

### PR DESCRIPTION
**Pull request by HarrisonB**
Closes #410.

### CODE REVIEW

**Comment by HarrisonB** [comment]
Is there something to look to for creating tests for items in `/lib/activity/`?

**Comment by yokkohsan** [comment]
When do you plan to merge this request?

**Comment by dval** [comment]
Any motion on this?

**Comment by bmitchinson** [comment]
Would love to see this soon if possible @tebriel

**Comment by iamswain25** [comment]
Why so long hesitation?

**Comment by tebriel** [comment]
@HarrisonB Thanks for this, I have a PR attached to our internal fork, but I think the main barrier to entry for this is that the Standard GitHub Slack App does not come with the `Gollum` event enabled. To enable this, we'll need to send notifications out to every organization that has the GitHub+Slack app installed and ask them to accept the updated permissions. I'm going to float this idea to our team, but I can't promise a timeline on how/when this can be merged given the large count of organizations that will need to enable accept the updated permissions for the Gollum events.

**Comment by HarrisonB** [comment]
> Thanks for this, I have a PR attached to our internal fork

Just so I understand this correctly, you have a copy of _this_ PR attached to the internal fork? Or another PR?

**Comment by tebriel** [comment]
@HarrisonB it's a copy of this PR, with the co-author attribute set issued against an internal fork.

**Comment by tkurki** [comment]
Any news on this? Roll my own or wait, that is the question.

**Comment by tebriel** [comment]
Hi @tkurki, unfortunately we likely will not be able to update the base slack app permissions at this time. We have a plan to do so later this year, but it's within the scope of a larger project of us migrating off of the legacy Slack Workspaces feature. The copy of your PR is still pending against our internal fork, but I cannot give you a timeline right now.

**Comment by tkurki** [comment]
Still relevant

**Comment by ashokirla** [comment]
Hi, Thanks for your contribution. We are going through platform changes to our ChatOps app and are not accepting any external contributions.  We will go through your PR and consider your suggestions if it aligns with our Product direction. We are converting your PR to a feature request and it can be tracked [here](https://github.com/integrations/slack/issues/1244).

**Pull request closed without merging**
