### PR TITLE
Notify issues.labeled required_labels [2]

### LINKED ISSUE #963: Mention requested reviewer chages after PR creation
It happens quite often that a reviewer is not picked on PR creation or an extra reviewer is added later on.
Unfortunately only a message is posted when a PR is created or closed. Getting mentions on the reviewer is immensely helpful.
Perhaps this can be fixed along with #961 or #832

### LINKED ISSUE #965: [Feature Request] Create notification on label change
In our Slack integration we limit notifications to a certain label.  Creating the PR and then changing the label doesn't trigger a notification.  It doesn't even trigger the notification if you add a comment later.

Here are the steps to recreate the problem:
1) subscribe to a repo with +label:ready-for-review
2) create a PR without a label
3) attach the label "ready-for-review"
4) notice that there is no notification in Slack for this PR
5) update the PR comment
6) notice that there is still no notification in Slack for this PR

NOTE: This is similar to these issues: #963, #961, #832

### PR DESCRIPTION
**Pull request by valerybugakov**
Duplicate #1058.

Credits to @otoyo for implementing this. 
This is the attempt to move this PR forward since it was approved months ago.

Fixes #965
Fixes #963

### CODE REVIEW

**Comment by valerybugakov** [comment]
@prashkan mentioning you, since you already reviewed this PR. 
Let me know if we can merge it.

**Review by prashkan — APPROVED** [review]

**Comment by prashkan** [comment]
@valerybugakov Looks good to me 👍🏽  We'd have to get approval from a codeowner, however, before this can merge.

**Comment by valerybugakov** [comment]
@prashkan oh, I thought that the previous PR was blocked because PR-owner wasn't merging it.
But both of them need an additional approval, right?

**Comment by prashkan** [comment]
> @prashkan oh, I thought that the previous PR was blocked because PR-owner wasn't merging it.
> But both of them need an additional approval, right?

That's right.

**Comment by valerybugakov** [comment]
Lol, sorry for the misunderstanding, then this PR is obsolete.

**Pull request closed without merging**
