### PR TITLE
WIP: Add reviewers filter

### PR DESCRIPTION
**Pull request by rugamaga**
This is implements filtering review requested users and teams
you can specify reviewer or team name by using +review like +label.

### CODE REVIEW

**Comment by zmoazeni** [comment]
Hi @rugamaga. Our team really appreciates contributions to help us maintain this slack integration. Thank you for taking the time and effort to get this PR submitted.

Before we dive further though, I do need to run this by one of our Product Managers. One question I have is that this overlaps with the [Scheduled Reminders feature](https://github.blog/2020-04-21-stay-on-top-of-your-code-reviews-with-scheduled-reminders/) we just launched.

Can you help us understand the usefulness of this in comparison to that feature? Some screenshots and use cases would go a long way!

Thanks! ❤️

**Comment by rugamaga** [comment]
Hi @zmoazeni Thanks to recommend Scheduled Reminder.
But It's not enough to our usecase.
Because we want to create realtime team-wise notification about PullRequest.
(Currently, they are always put they PullRequest themselves on conversation slack channel. They can't wait next reminder, so realtime is needed.)

Our company have some of company-wide repository and split review responsibility into team by CODEOWNERS. so if this feature implemented very helpful.

**Comment by errygg** [comment]
+ 1

**Comment by Masacre23** [comment]
+1

**Comment by plauche** [comment]
@zmoazeni any updates on how this fits into your product roadmap? I would **love** to have a GitHub Slack channel which sends me real-time updates only for PRs that I'm a reviewer on, and I think this filter would enable that.

**Comment by zmoazeni** [comment]
I have moved to another area within GitHub and am no longer working on the Slack integration and Scheduled reminders, however that team is focusing on those are still keeping tabs on this conversation (and others).

**Comment by rugamaga** [comment]
This feature's alternative is already officially implemented: https://github.com/integrations/slack/issues/380#issuecomment-636068304
So I've close this PullRequest thanks for the effort of the team.

**Pull request closed without merging**
