### PR TITLE
Adds capability of ignoring selected label in the subscription

### PR DESCRIPTION
**Pull request by potiuk**
This change implements issue #951 - you can specify -label if you
want to ignore pull requests with the specified label.

### CODE REVIEW

**Comment by potiuk** [comment]
Note! I had some troubles with testing it fully with my development version of the plugin - I could not make it works from my local machine even with ngrok following step-by-step intros from the CCONTRIBUTING.md  guide. So while I wrote all the unit tests and they all pass I could only test it up to the level that I could see the commands added in my slack:

Screenshot 2020-01-02 at 03 03 13

And the messages get parsed properly and sent to my app. I could see them coming properly parsed, However there was a problem coming likely from some configuration problem of the application (even though I followed closely the instructions):

Screenshot 2020-01-02 at 03 02 34

I'd appreciate if you could help with some hints what I might have missed in the configuration (the error is about missing user when I enabled TRACE log level as you can see above) or maybe you can test it more easily in your environment.

Happy New Year and looking forward to contribute to github/slack integration!

**Comment by mik-laj** [comment]
That's what I miss in this integration. This is a much-awaited feature.

**Comment by davidpaulsson** [comment]
Eagerly awaiting this!

**Comment by potiuk** [comment]
Hello @tebriel - is anything happening with the repo now? Seems that would be a nice feature to add?

**Comment by potiuk** [comment]
Hey @dennissivia  ? Any chance for a slight interest in PRs? Or should we treat that repository and slack integration as dead? It certainly looks like it is so. 

Or is it coincidence that last commit merged was in September and "Microsoft (Teams!) - Github" deal closed in October.

Maybe simply announce the integration dead so that others can pick it up - plain and straightforward ?

**Comment by tebriel** [comment]
@potiuk First, I want to thank you for this contribution. This feature sounds really cool, useful, and like a great thing to add to the Slack Functionality.

This repo *is* still under development, but currently all resources are working towards:
1.  Releasing [Scheduled Reminders](https://github.blog/changelog/2019-11-14-scheduled-reminders-beta/) announced at Universe.
2. Moving the Slack service from its temporary deployment location to a more permanent one in line with deployment criteria for services at GitHub.
3. Fixing bugs in the backlog that are preventing use of current features (like `/github deploy` which works for some, but fails on a few common use cases).

Unfortunately (for you and us!) we haven't had the time to dedicate to reviewing, approving, merging, and deploying community contributed pull requests. I promise we want to get to them, but right now we don't have enough time to manage the above priorities and handle the community contributions. As soon as we get Slack Deployed to its permanent location and Scheduled Reminders GA'd, we should be able to start making improvements to the lives of users of Slack like this PR that you have submitted, which I truly hope to be able to do soon. I don't have a public timeline I can share, but the team and I are working as fast as we can to get these things out the door.

Thank you for your contributions, understanding, and patience!
Chris

**Comment by potiuk** [comment]
> Thank you for your contributions, understanding, and patience!
> Chris

Thanks for the info! I think the most disturbing part was the silence :). We simply did not know what to expect and that was a bit unnerving. After the explanation I am more confident that it will be good :). Also sorry for jumping to conclusions too quickly, apologies. I have a big faith in Github, it's fantastic service that brought the communities of developers to a higher level. I even pay my `pro` subscription even if I do not need it technically any more. 

It's great to see that things are moving in the right direction and helping developer's communities to grow!

**Comment by tebriel** [comment]
@potiuk Thank you. We're having an internal discussion at our next team sync about how to clearly communicate expectations, explicit over implicit process, and response times to improve this process. We appreciate your candid feedback and response here!

**Comment by erenkabakci** [comment]
Hi! Is there any timeline regarding this PR. It's a very useful feature to reduce pollution in channels. We would love to have this.

**Comment by tebriel** [comment]
@erenkabakci Hi and thank you for asking. Right now we do not have a timeline, we're still hard at work on the priorities I [outlined above](https://github.com/integrations/slack/pull/974#issuecomment-579268357). I know that reducing noise pollution in slack channels is crucial, and I want to consider this Pull Request, but I can't commit to any time frame at the moment. Thank you for understanding!

**Comment by noam-c** [comment]
@tebriel Hi Chris! As it's been a couple of months, I just wanted to see if there is any update on the timeline for this PR. It has a pretty outsized impact on how we can get the most out of this integration.

Thank you for your help and all the effort you've put into the Github/Slack integration thus far!

**Comment by jccr** [comment]
My team enjoys the slack integrations very much, it helps us stay in the loop while the whole team is working remotely.
The lack of the feature to filter out noisy bot-generated PRs has been giving us some pain.
Looking forward to the updates on this :+1:

**Comment by tebriel** [comment]
@noam-c @jccr Hi friends, I know this is important to your workflow and reducing noise, but right now we don't have bandwidth to prioritize this change. It is on our radar and listed in our backlog. I'm sorry I don't have better news for you at this time!

**Comment by potiuk** [comment]
I am closing this one, there does not seem to be interest from the github team . Github team - please reopen if you find it valuable.

**Comment by pforrence-inquirer** [comment]
Please reopen! Github team, let us know if there's any update on your availability!

**Comment by pirroh** [comment]
Adding my voice to the choir -- please reopen and prioritize this PR!
Without being able to filter the traffic generated by bots (e.g., @dependabot), the Slack integration becomes practically useless.

**Comment by fharper** [comment]
I would love to see this PR reopen! It would give us the possibility to not get notifications for bots as one example.

**Comment by ramraphael** [comment]
Chiming in to increase visibility. This would be a really really useful feature to cut down on noise.

**Comment by NinoFloris** [comment]
@potiuk please reopen, as mentioned here, they have had an ownership change of the team. hopefully this will improve responsiveness.
https://github.com/integrations/slack/issues/1103#issuecomment-755265620

**Comment by potiuk** [comment]
Not sure If I have time to follow on this one though. This has long time dropped off my priority list

**Comment by pforrence-inquirer** [comment]
@potiuk Is there anyone else who can work it?

**Comment by potiuk** [comment]
I am completely not in a position to find anyone, sorry. 

Unfortunately all of my team has now moved away from this and we use alternatives.

It has been  abandoneed and ignored for far too long to be valid for us any more. I really wanted to fix it a year ago. I had to search for alternatives, (which I found) and I am not able to spend any time neither fixing, nor finding someone.

But if you find anyone to take it over from here - feel free. Treat is a as royalty free piece of code without any claims from my side. I am happy even not being mentioned  as an author if anyone takes it over.

**Comment by sgarner** [comment]
It looks like the feature is already complete and just needs a review from a project maintainer?

If any changes are required, I'm sure there are enough people in this thread who wants this feature (myself included) who can help out to get it across the line!

**Comment by potiuk** [comment]
Please @sgarner !. And yes - it was complete then :)

**Comment by potiuk** [comment]
I am closing this one as I am closing all PRs which I am not working on - feel free to take the code and complete it though

**Comment by Nesox** [comment]
@potiuk  I would love this functionality for Slack, `dependabot[bot]` is really a pain and it would be lovely to be able to filter out notifications based on labels ❤️

**Comment by sethfri** [comment]
@tebriel Do you mind giving us an update on GitHub's level of support for the Slack integration? It looks like the last time any code in this repo changed was in 2019. Maybe it would be a good idea to identify some community maintainers, as based on the issue queue there seems to be a lot of demand for improvements. Thank you!

**Comment by tebriel** [comment]
@gauravsaralMs I know your team is working on communicating plans/work/ideas, if you can provide any feedback/information for @sethfri, that would be great. Thank you!

**Comment by gauravsaralMs** [comment]
adding @ashokirla

**Comment by marcmetz** [comment]
+1 dependabot is sending constant messages — otherwise, the Slack integration would be very useful.

**Comment by jmredfern** [comment]
adding my voice to the choir, there's no way to silence dependabot without this feature!

**Comment by sethfri** [comment]
@gauravsaralMs @ashokirla Any updates?

**Comment by SkylerSeamans** [comment]
Bumping for our team as well - without this, the integration doesn't work for us. We have far too many repos with dependabot running.

**Comment by Robula** [comment]
Come on, we need the ability to filter out `dependabot`/`renovate` spam via labels.

**Comment by aji** [comment]
+1 on this, we are being forced to choose between dependabot and the slack integration, and keeping our dependencies updated is much more important to us

**Comment by Nesox** [comment]
+1 here as well, we want to filter out Dependabot messages from Slack but it's a bit tricky, having this would be awesome!

**Comment by ChaseMarcum** [comment]
+1 dependabot is sending constant messages — otherwise, the Slack integration would be very useful.

**Comment by JKetelaar** [comment]
+1 for having label ignore listing

**Comment by yudppp** [comment]
I created new PR ( #1252 ).

But I was commented this following.

> We are currently not accepting any contributions to this app. You can raise a feature request from here

https://github.com/integrations/slack/pull/1252#issuecomment-874105570

**Pull request closed without merging**
