### PR TITLE
Send Slack notificaitons when the user is set as a reviewer of a pull request.

### PR DESCRIPTION
**Pull request by gorohash**
This feature is requested at #382

A user will be able to receive Slack notificaitons when the user is set as a reviewer of a pull request.
To notify a user, the user should enter the following command:
`/github subscribe */* review_requests`

Please merge!!! :)

### CODE REVIEW

**Comment by gorohash** [comment]
@gimenete & @wilhelmklopp 
I've added some changes to improve testing coverage.
Please review this PR!

**Comment by gorohash** [comment]
@gimenete & @wilhelmklopp 
We've resolved conflict.
Please review this pull request!

**Comment by huehnerlady** [comment]
Is there any update on this? It sounds like an awesome feature but seems to be dead for nearly 2 months now?

**Comment by VizualAbstract** [comment]
Any update on this? Our team would love to take advantage of this to alert them when someone has requested a review from our team.

**Comment by cjcbusatto** [comment]
For our team that would be also a must-have feature. 
At the moment, our Slack channels are polluted of messages and sometimes the PR ones are skipped. 
It would be awesome to direct notify a reviewer about the request.

**Comment by tekstrand** [comment]
Code looks good. Needs a rebase now. What is the process for getting this merged? @wilhelmklopp  @gimenete

**Comment by gio-built** [comment]
This.

**Comment by ftruzzi** [comment]
+1 for this, we need it as well.

@tebriel as the most recent committer here, maybe you can help? Thanks

**Comment by tebriel** [comment]
This functionality exists in the new [Scheduled Reminders](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-pull-requests) feature set. Can you try that out and let us know if there are any pieces missing? The beta is open and you can join by signing up [here](https://github.com/features/reminders/signup)!

**Comment by rmacklin** [comment]
@tebriel Thanks for chiming in! I signed up for the beta, but I'm having a bit of trouble finding this in the Scheduled Reminders settings. Those settings seem to be focused on Slack notifications to remind you of pull requests with outstanding review requests.

What my team is looking for is a way to get a Slack notification immediately after the `pull_request.review_requested` event, rather than on some scheduled interval. If this is possible, can you share some screenshots of how to set this up?

**Comment by rmacklin** [comment]
@tekstrand Thanks. It took me a moment to realize you were talking about a different page. I was looking at `https://github.com/organizations/<org_name>/settings/reminders/new` which looks like

image

whereas your screenshot is from this other page: `https://github.com/settings/reminders/<org_name>`.

That said, it seems like those settings don't allow you to configure a Slack channel to receive the notifications - they'll always come as DMs. I think having the option to subscribe a channel to receive notifications for the `pull_request.review_requested` is still useful, particularly for workflows where the PR author always requests review from a GitHub Team rather than from individual users.

**Comment by A-styler** [comment]
+1 for this, we need it as well.

**Comment by Masacre23** [comment]
+1

**Comment by alexroitman** [comment]
Thanks u!! can we merge this?

**Review by alexroitman — APPROVED** [review]
PLSS!

**Comment by germanflighel** [comment]
This is a must have! Please merge!

**Comment by smalhotra3599** [comment]
@gorohash @alexroitman see my last comment

**Comment by andresovela** [comment]
+1 we need this too! Please consider merging soon! :)

**Comment by dkelly-sighter** [comment]
This would be amazing!

**Comment by ashokirla** [comment]
Hi, Thanks for your contribution. We are going through platform changes to our ChatOps app and are not accepting any external contributions.  We will go through your PR and consider your suggestions if it aligns with our Product direction. We are converting your PR to a feature request and it can be tracked [here](https://github.com/integrations/slack/issues/1243).

**Comment by jvenne-bravado** [comment]
Why as this never merged??

**Pull request closed without merging**
