### PR TITLE
Add /github settings

### PR DESCRIPTION
**Pull request by wilhelmklopp**
Implements `/github settings` to remove repos from auto-unfurls and unmute muted prompts

image

Todo:
- [x] Integration tests
- [x] -> /lib/messages
- [x] Add entry in `/github help`

### CODE REVIEW

**Comment by ppamorim** [comment]
Is this working? When I do `/github settings` it returns `You do not have any settings configured.`. How to add a configuration?

**Comment by wilhelmklopp** [comment]
@ppamorim what setting would you like to configure?

**Comment by creichert** [comment]
Mine says the same thing `You do not have any settings configured.`. Really, just a couple examples would be nice. I don't know what settings I would like to configure yet. For new issues created, I would like the title of the issue in the desktop notification (is that possible like in the GitHub legacy slack app)?

**Comment by wilhelmklopp** [comment]
`/github settings` is currently only for individual user settings relating to unfurls. 

Examples for repo level subscription configurations are here: https://github.com/integrations/slack#configuration

> For new issues created, I would like the title of the issue in the desktop notification (is that possible like in the GitHub legacy slack app)?

I don't think it'll currently show the title of the issue. Only something to the effect of "[integrations/slack] Issue opened by creichert" -- but feel free to open an issue on this repo for this improvement

**Comment by creichert** [comment]
@wilhelmklopp Perfect, thanks!

**Comment by matkoch** [comment]
The thing is that `/github help` reveals `settings` as a command, but after invoking `/github settings` this doesn't give the user any clue of what it can do. More documentation would be really appreciated.

**Comment by say8425** [comment]
@matkoch I agree. Also this `settings` command is not for most of users. So I think change the command name.

**Comment by nevir** [comment]
How do we use this command to adjust unfurl settings?

**Pull request merged**
